SIGNUPNAME = "xpath = //*[@data-qa='signup-name']"
SIGNUPEMAIL = "xpath = //*[@data-qa='signup-email']"
LOGINEMAIL = "xpath = //*[@data-qa='login-email']"
LOGINPASSWORD = "xpath = //*[@data-qa='login-password']"
CREATEACCOUNT = "xpath = //*[@data-qa='create-account']"
SCROLLTOVIEW = "xpath=//p[@class='pull-left']"
BLUETOPVIEW = "//a[@href='/product_details/1']"
FIRSTNAMEADDRESS = "css:#address_delivery .address_firstname"
ADDRESS1 = "xpath:(//*[@class='address_address1 address_address2'])[2]"
CITY = "css:#address_delivery .address_city"
COUNTRY = "css:#address_delivery .address_country_name"
MOBILENUM = "css:#address_delivery .address_phone"
BLUETOP = "xpath://*[@data-product-id='1']"
CARTCHECKOUT = "xpath://*[@class='btn btn-default check_out']"
STYLISHDRESS = "xpath://*[@data-product-id='4']"